### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by nhatcher** [ironcalc/ironcalc.github.io#2]
The Logo could be based on the Hat. Maybe @nhatcher could prepare a blogpost explaining the Logo and its connections to IronCalc.

Something to play with:

https://github.com/ironcalc/IronCalc/tree/main/assets

Also we could create a Mascot:

Like Rust has Ferris as a mascot or sea-orm has Terres:

https://github.com/SeaQL/sea-orm

I think life is better with an official mascot.

**Comment by marke-apexit** [comment]
Sharing an idea for a logo, it isn't mascot based, but I think it is evocative of "iron calc."  The idea is a steam punk aesthetic with a spreadsheet that is spiral bound and a gear.

First the SVG version of the icon:
![Image](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/f8a6ca9a-3c99-43c8-a39e-895f3c92f745)

And to demonstrate legibility at various resolutions:

| size | icon |
| - | - |
| 256x256 | ![Image](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/21ab8aa3-f7d0-47f1-9d01-3533d590e71f) |
| 64x64 | ![Image](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/6565901f-c96f-4335-a3f4-48e99a4e3294) |
| 48x48 | ![Image](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/bc3d6e59-4995-4e36-9ae6-e6741688cfcd) |
| 16x16 | ![Image](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/14e928f3-d914-4552-b13a-07423025072d) |

I could make the SVG line weight a bit lighter and I think it could improve the 16x16 icon without having a negative impact on the larger icons.  But even as is, it is recognizable at 16x16.

Of course this icon can also be colorized. Below is an example borrowing from a steampunk color pallette.

![Image](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/7e62d4f3-f8de-41a4-af80-f37bb685b5bc)

**Comment by marke-apexit** [comment]
@nhatcher I thought I recognized that "aperiodic monotile" when I saw it!  It probably comes down to "branding" and easy recognition on a desktop, file explorer, and favicon.

@nhatcher Below are a few alternative colorized SVG icons borrowed from the Figma color pallete you shared.  If you would like to suggest colors from that pallete for the three main elements (rings, gear, sheet) I would be happy to create that SVG.

![ironcalc_icon_color2](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/f85d28b4-1fdd-4d5e-9102-7d742aaece9b)

![ironcalc_icon_color3](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/5159b40e-74ea-4eb6-8595-53d6d027979d)

![ironcalc_icon_color4](https://github.com/ironcalc/ironcalc.github.io/assets/98044139/91873d86-9f96-4250-be1b-e17e887b46b5)

I prefer the first or last, representing high and low color contrast.  The middle one looks strange to me with a mix of the two.

**Comment by nhatcher** [comment]
Hi @marke-apexit, TBH they look lovely. I've been doing some testing and I like it. Thank you very much!
I would go for the last one. I want to discuss this with our lead designer because I know he has put some thought into this. He is traveling ATM for another few weeks, so it will be a while, but I'd like to try it out.

**Comment by nhatcher** [comment]
Hi @marke-apexit, thanks for your input! We had some long discussions this week and presented a bunch of different logos, including yours and variations to some people from designers to developers to all kinds of folks and ended up setting for a simple Logo. We might in the future use your design for something else if you don't mind
